# Generated by Django 5.1.4 on 2025-02-28 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fakultet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255, verbose_name='Fakultet nomi')),
            ],
        ),
        migrations.CreateModel(
            name='OqishKursi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255, verbose_name="O'qish kursi")),
            ],
        ),
        migrations.CreateModel(
            name='OqishTili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255, verbose_name="O'qish tili")),
            ],
        ),
        migrations.CreateModel(
            name='OqishTuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255, verbose_name="O'qish turi")),
            ],
        ),
        migrations.CreateModel(
            name='Yonalish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255, verbose_name="Yo'nalish nomi")),
                ('kodi', models.CharField(max_length=255, verbose_name="Yo'nalish kodi")),
            ],
        ),
        migrations.CreateModel(
            name='Transkript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toliq_ism', models.CharField(max_length=255, verbose_name="To'liq ismi")),
                ('tugatgan_yili', models.CharField(max_length=255, verbose_name='Tugatgan yili')),
                ('student_id', models.CharField(max_length=255, unique=True, verbose_name='Student ID')),
                ('fakultet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transkript_app.fakultet', verbose_name='Fakultet')),
                ('oqish_kursi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transkript_app.oqishkursi', verbose_name="O'qish kursi")),
                ('oqish_tili', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transkript_app.oqishtili', verbose_name="O'qish tili")),
                ('oqish_turi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transkript_app.oqishturi', verbose_name="O'qish turi")),
                ('yonalish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transkript_app.yonalish', verbose_name="Yo'nalish")),
            ],
        ),
    ]
