# Generated by Django 5.1.4 on 2025-02-28 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transkript_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fakultet',
            options={'verbose_name': 'Fakultet', 'verbose_name_plural': 'Fakultetlar'},
        ),
        migrations.AlterModelOptions(
            name='oqishkursi',
            options={'verbose_name': "O'qish kursi", 'verbose_name_plural': "O'qish kurslari"},
        ),
        migrations.AlterModelOptions(
            name='oqishtili',
            options={'verbose_name': "O'qish tili", 'verbose_name_plural': "O'qish tillari"},
        ),
        migrations.AlterModelOptions(
            name='oqishturi',
            options={'verbose_name': "O'qish turi", 'verbose_name_plural': "O'qish turlari"},
        ),
        migrations.AlterModelOptions(
            name='transkript',
            options={'verbose_name': 'Transkript', 'verbose_name_plural': 'Transkriptlar'},
        ),
        migrations.AlterModelOptions(
            name='yonalish',
            options={'verbose_name': "Yo'nalish", 'verbose_name_plural': "Yo'nalishlar"},
        ),
    ]
