# Generated by Django 5.1.4 on 2025-02-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transkript_app', '0002_alter_fakultet_options_alter_oqishkursi_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transkript',
            name='transkript_pdf',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Transkript PDF'),
        ),
    ]
