# Generated by Django 5.1.4 on 2025-03-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transkript_app', '0003_transkript_transkript_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transkript',
            name='student_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Student ID'),
        ),
    ]
