# Generated by Django 5.1.4 on 2025-03-02 09:27

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transkript_app', '0004_alter_transkript_student_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTranskript',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('toliq_ism', models.CharField(max_length=255, verbose_name="To'liq ismi")),
                ('tugatgan_yili', models.CharField(max_length=255, verbose_name='Tugatgan yili')),
                ('student_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Student ID')),
                ('transkript_pdf', models.TextField(blank=True, max_length=100, null=True, verbose_name='Transkript PDF')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('fakultet', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transkript_app.fakultet', verbose_name='Fakultet')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('oqish_kursi', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transkript_app.oqishkursi', verbose_name="O'qish kursi")),
                ('oqish_tili', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transkript_app.oqishtili', verbose_name="O'qish tili")),
                ('oqish_turi', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transkript_app.oqishturi', verbose_name="O'qish turi")),
                ('yonalish', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transkript_app.yonalish', verbose_name="Yo'nalish")),
            ],
            options={
                'verbose_name': 'historical Transkript',
                'verbose_name_plural': 'historical Transkriptlar',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
