# Generated by Django 5.1.4 on 2025-03-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transkript_app', '0005_historicaltranskript'),
    ]

    operations = [
        migrations.AddField(
            model_name='yonalish',
            name='shablon_docx',
            field=models.FileField(blank=True, null=True, upload_to='shablons/', verbose_name='Shablon DOCX'),
        ),
    ]
