# Generated by Django 5.1.4 on 2025-03-09 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transkript_app', '0006_yonalish_shablon_docx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255, verbose_name='Fan nomi')),
                ('yonalish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transkript_app.yonalish', verbose_name="Yo'nalish")),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
            },
        ),
    ]
