# Generated by Django 5.1.4 on 2025-03-10 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transkript_app', '0007_fan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fan',
            name='yonalish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fanlar', to='transkript_app.yonalish', verbose_name="Yo'nalish"),
        ),
    ]
