# Generated by Django 5.1.7 on 2025-04-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transkript_app', '0008_alter_fan_yonalish'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltranskript',
            name='year',
            field=models.CharField(default='20.07.2022', max_length=255),
        ),
        migrations.AddField(
            model_name='transkript',
            name='year',
            field=models.CharField(default='20.07.2022', max_length=255),
        ),
    ]
