# Generated by Django 5.1.7 on 2025-06-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transkript_app', '0009_historicaltranskript_year_transkript_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltranskript',
            name='year',
            field=models.CharField(default='24.08.2022', max_length=255),
        ),
        migrations.AlterField(
            model_name='transkript',
            name='year',
            field=models.CharField(default='24.08.2022', max_length=255),
        ),
    ]
