# Generated by Django 5.1.7 on 2025-06-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transkript_app', '0010_alter_historicaltranskript_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltranskript',
            name='tugatgan_yili',
            field=models.CharField(default='2022', max_length=255, verbose_name="O'qishga kirgan yili"),
        ),
        migrations.AlterField(
            model_name='transkript',
            name='tugatgan_yili',
            field=models.CharField(default='2022', max_length=255, verbose_name="O'qishga kirgan yili"),
        ),
    ]
