# Generated by Django 5.1.4 on 2025-02-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sayt nomi')),
                ('favicon', models.FileField(upload_to='favicons/', verbose_name='Favicon')),
                ('site_author', models.TextField(verbose_name='Sayt muallifi')),
                ('site_keywords', models.TextField(verbose_name='Sayt kalit so‘zlari')),
                ('site_description', models.TextField(verbose_name='Sayt tavsifi')),
            ],
            options={
                'verbose_name': 'SEO Sozlamasi',
                'verbose_name_plural': 'SEO Sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_logo', models.ImageField(upload_to='logos/', verbose_name='Bosh logo')),
                ('footer_logo', models.ImageField(upload_to='logos/', verbose_name='Pastki logo')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Telefon raqami')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzil')),
                ('footer_text', models.TextField(verbose_name='Pastki matn')),
                ('copyright_text', models.TextField(verbose_name='Mualliflik huquqi matni')),
            ],
            options={
                'verbose_name': 'Sayt Sozlamasi',
                'verbose_name_plural': 'Sayt Sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='SocialNetworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('icon', models.CharField(max_length=255, verbose_name='Ikonkasi')),
                ('link', models.CharField(max_length=255, verbose_name='Havolasi')),
            ],
            options={
                'verbose_name': 'Ijtimoiy Tarmoq',
                'verbose_name_plural': 'Ijtimoiy Tarmoqlar',
            },
        ),
        migrations.CreateModel(
            name='TelegramBotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='Bot usernamesi')),
                ('token', models.TextField(verbose_name='Tokeni')),
                ('admins', models.CharField(max_length=255, verbose_name='Adminlar')),
            ],
            options={
                'verbose_name': 'Telegram Bot Konfiguratsiyasi',
                'verbose_name_plural': 'Telegram Bot Konfiguratsiyalari',
            },
        ),
    ]
